### PR TITLE
latest currie and related madness

### PR DESCRIPTION
**Pull request by swfiua**

### CODE REVIEW

**Comment by Tigercardell** [comment]
trying to run it in windows, re-commented out imageio after a "no module named imageio found" error, then got this error when i ran it again:

UnboundLocalError: local variable 'im' referenced before assignment

**Comment by swfiua** [comment]
I think this pull request fixes that.

**Comment by Tigercardell** [comment]
*I pulled from swfiua/karmapi, should have mentioned that in the last comment

**Comment by swfiua** [comment]
can you post the full stack trace so I can see where it is when the exception goes off?

**Comment by Tigercardell** [comment]
Sure, one moment

**Comment by Tigercardell** [comment]
$ python -m karmapi.currie
OSError exception number 0 from selector_select ignored
Curio: Task Crash: PigFarm.build
Traceback (most recent call last):
  File "c:\users\gina\devel\curio\curio\kernel.py", line 860, in _run
    trap = current._send(current.next_value)
  File "C:\Users\Gina\devel\swfiuakarmapiwin\karmapi\karmapi\currie.py", line 88, in build
    piglet = meta(self.eloop.app.winfo_toplevel(), **kwargs)
  File "C:\Users\Gina\devel\swfiuakarmapiwin\karmapi\karmapi\tankrain.py", line 56, in __init__
    super().__init__(parent)
  File "C:\Users\Gina\devel\swfiuakarmapiwin\karmapi\karmapi\piglet.py", line 540, in __init__
    super().__init__(parent, **kwargs)
  File "C:\Users\Gina\devel\swfiuakarmapiwin\karmapi\karmapi\backends\tkpig.py", line 237, in __init__
    self.compute_data()
  File "C:\Users\Gina\devel\swfiuakarmapiwin\karmapi\karmapi\tankrain.py", line 82, in compute_data
    self.data = im
UnboundLocalError: local variable 'im' referenced before assignment

**Comment by swfiua** [comment]
OK -- so the problem is tankrain.

I have it hard-wired to point at some images I grabbed during Nicole.

You don't have the images, so it has an empty list.

Try the latest commit, it should show a rainbow if no tankrain data.

**Comment by Tigercardell** [comment]
okay, pulled the latest, all command line says is this:
$ python -m karmapi.currie
OSError exception number 0 from selector_select ignored

but the tk window is still blank.

**Comment by swfiua** [comment]
OK, so to move back and forwards through widgets you need keyboard focus in the tk window and use:

n: next widget
p: previous widget

It remains blank until you press n or p to start cycling through the widgets

**Comment by Tigercardell** [comment]
okay, fired it back up and at first it didnt seem to be doing anything, but after pressing n a few times I got to the swarm of bats.

**Comment by Tigercardell** [comment]
everything seems to be working fine, however there are 8 blank widgets between the clock and the bats as i scroll through with n. I assume those are images i'm missing.

**Comment by swfiua** [comment]
That's right -- I should really fix the thing up to get the list of images from elsewhere.

I should at least fix it to have an image window with a title and no image if the image file is AWOL.

Or rather -- a list of widgets + parameters.   Then currie could run whatever you want and we can just have some examples.

But at least you are up and running for now.

**Pull request merged**
