### PR TITLE
start of sound stuff

### PR DESCRIPTION
**Pull request by Ka1lon**

### CODE REVIEW

**Comment by swfiua** [comment]
So issue1 is still a thing.  Is the hog a pig? 

I like the hush name.  For sound.   Hush: filters out the noise.

**Comment by Ka1lon** [comment]
pigs running around in the belly of a python sounds apt as they would be
rather hushed in there

**Comment by swfiua** [comment]
true.  I think this could be any signal coming in from the pigs.. or elsewhere for that matter.

But for now, lets do sound.

The rough plan is to get a task that is busy listening to the source and collecting frames.

curio has stuff to do most of what is needed.

with that we can start processing frames elsewhere, turn them into pictures, notes, beats whatever.

**Comment by swfiua** [comment]
oh and a guitar tuner would be good to have...

**Pull request merged**
